export default [
  "I wake up early on weekdays.",
  "She usually drinks coffee before work.",
  "They play badminton every Saturday.",
  "He studies English after dinner.",
  "We often take the bus to school.",
  "My brother reads news online each morning.",
  "The shop opens at nine o’clock.",
  "I rarely eat fast food these days.",
  "She doesn’t like loud music.",
  "They do not drive to the office on Fridays.",
  "He doesn’t watch TV during dinner.",
  "We don’t have classes on Sunday.",
  "I do not understand this rule.",
  "She doesn’t speak too quickly in meetings.",
  "They don’t agree with that idea.",
  "Do you work from home sometimes?",
  "Does she live near the station?",
  "Do they study together after class?",
  "Does he need help with the report?",
  "Do we have time for one more question?",
  "I am writing an email right now.",
  "She is waiting for the train.",
  "They are watching a documentary tonight.",
  "He is learning to cook these days.",
  "We are preparing for the exam this week.",
  "I am not feeling well today.",
  "She isn’t answering her phone.",
  "They are not listening to the instructions.",
  "He isn’t using social media this month.",
  "We are not working late tonight.",
  "Am I speaking too fast?",
  "Is she coming to the meeting?",
  "Are they practicing for the presentation?",
  "Is he studying in the library?",
  "Are we meeting at six?",
  "I have finished my homework already.",
  "She has visited that museum twice.",
  "They have started a new project this month.",
  "He has learned many new words recently.",
  "We have seen this movie before.",
  "I haven’t eaten breakfast yet.",
  "She has not replied to my message.",
  "They haven’t completed the assignment.",
  "He has not called me today.",
  "We haven’t decided the plan yet.",
  "Have you ever tried coding?",
  "Has she finished the report?",
  "Have they seen the new schedule?",
  "Has he applied for the job?",
  "Have we missed the deadline?",
  "I have been studying for two hours.",
  "She has been working here since June.",
  "They have been waiting for a long time.",
  "He has been practicing guitar every day.",
  "We have been saving money for months.",
  "I haven’t been sleeping well lately.",
  "She has not been feeling confident recently.",
  "They haven’t been paying attention in class.",
  "He has not been exercising this week.",
  "We haven’t been communicating clearly.",
  "Have you been working a lot lately?",
  "Has she been traveling this month?",
  "Have they been using the new system?",
  "Has he been studying enough?",
  "Have we been following the instructions?",
  "I worked late yesterday.",
  "She watched a movie last night.",
  "They visited their grandparents last weekend.",
  "He called me after lunch.",
  "We studied together yesterday evening.",
  "I didn’t go out yesterday.",
  "She did not join the group chat.",
  "They didn’t finish the project on time.",
  "He did not answer my question.",
  "We didn’t take a taxi.",
  "Did you see the message?",
  "Did she submit the assignment?",
  "Did they arrive on time?",
  "Did he forget the password?",
  "Did we meet last month?",
  "I was working when you called.",
  "She was cooking while I cleaned.",
  "They were talking during the lecture.",
  "He was driving when it started raining.",
  "We were studying all afternoon.",
  "I wasn’t listening at that moment.",
  "She was not feeling well yesterday.",
  "They weren’t paying attention.",
  "He was not using his phone then.",
  "We weren’t arguing, just discussing.",
  "Was I being rude?",
  "Was she waiting for you?",
  "Were they working last night?",
  "Was he sleeping when you arrived?",
  "Were we sitting in the wrong room?",
  "I had finished the task before noon.",
  "She had left before I arrived.",
  "They had eaten dinner already.",
  "He had studied for the test earlier.",
  "We had booked the tickets in advance.",
  "I hadn’t seen that email before.",
  "She had not heard the news yet.",
  "They hadn’t met the new teacher.",
  "He had not saved the file.",
  "We hadn’t planned for delays.",
  "Had you finished the report before the meeting?",
  "Had she moved to a new place?",
  "Had they started the class earlier?",
  "Had he forgotten the appointment?",
  "Had we made the same mistake before?",
  "I had been working for hours before I rested.",
  "She had been studying all day before dinner.",
  "They had been waiting for weeks before the result.",
  "He had been training hard before the match.",
  "We had been discussing the plan before we agreed.",
  "I hadn’t been sleeping well before the holiday.",
  "She had not been practicing enough before the test.",
  "They hadn’t been following the rules before the warning.",
  "He had not been saving money before the trip.",
  "We hadn’t been communicating well before the problem.",
  "Had you been working there long before you left?",
  "Had she been learning English before college?",
  "Had they been preparing before the event?",
  "Had he been driving long before the break?",
  "Had we been waiting too long before we called?",
  "I will call you later.",
  "She will join the meeting tomorrow.",
  "They will finish the project next week.",
  "He will explain the plan soon.",
  "We will travel next month.",
  "I won’t be late tomorrow.",
  "She will not share the password.",
  "They won’t cancel the trip.",
  "He will not ignore the message.",
  "We won’t forget the deadline.",
  "Will you help me later?",
  "Will she come to the party?",
  "Will they accept the offer?",
  "Will he arrive on time?",
  "Will we need more time?",
  "I am going to start a new course.",
  "She is going to buy a new laptop.",
  "They are going to move next year.",
  "He is going to call his parents tonight.",
  "We are going to meet after work.",
  "I am not going to argue about it.",
  "She isn’t going to quit her job.",
  "They are not going to change the rules.",
  "He is not going to skip the class.",
  "We aren’t going to rush the decision.",
  "Are you going to join us?",
  "Is she going to study abroad?",
  "Are they going to fix the issue?",
  "Is he going to apologize?",
  "Are we going to leave now?",
  "If I have time, I will read more.",
  "If she calls, I will answer.",
  "If they arrive early, we will start.",
  "If he is tired, he will rest.",
  "If we plan well, we will succeed.",
  "I can help you with that.",
  "She can explain it clearly.",
  "They can finish faster with teamwork.",
  "He can’t attend the meeting today.",
  "We can’t wait too long.",
  "You should drink more water.",
  "She should take a short break.",
  "They should review the notes again.",
  "He shouldn’t skip breakfast.",
  "We should not waste time.",
  "I must submit the form today.",
  "She must wear an ID badge here.",
  "They must follow the safety rules.",
  "He mustn’t park in that area.",
  "We must not forget the documents.",
  "I might go out tonight.",
  "She might be busy right now.",
  "They might change the schedule.",
  "He might not come today.",
  "We might not have enough seats.",
  "I would like to learn faster.",
  "She would rather stay home tonight.",
  "They would choose a cheaper option.",
  "He would not accept that excuse.",
  "We would be happier with a clear plan.",
  "This task is easier than the last one.",
  "Her explanation is clearer than mine.",
  "Their office is bigger than ours.",
  "His idea is better than before.",
  "Our team is stronger than last year.",
  "This is the best option for now.",
  "She is the most organized person here.",
  "They chose the fastest route home.",
  "He gave the worst excuse today.",
  "We had the most important meeting yesterday.",
  "I have a meeting at 3 PM.",
  "She has two assignments this week.",
  "They have a new manager now.",
  "He has an appointment tomorrow morning.",
  "We have a plan for the weekend.",
  "There is a problem with the printer.",
  "There are many people in the room.",
  "There was a delay this morning.",
  "There were no seats left.",
  "There will be a test next Monday.",
  "I used to play games every day.",
  "She used to live near the beach.",
  "They used to work in the same office.",
  "He didn’t use to wake up early.",
  "We used to study together after class.",
  "Please speak more slowly.",
  "Could you repeat that, please?",
  "Let’s meet at the library.",
  "Don’t touch that button.",
  "Please don’t be late again.",
  "I think this idea will work.",
  "She believes the plan is risky.",
  "They hope to finish early today.",
  "He feels nervous before presentations.",
  "We know the answer already.",
  "I am excited about the new project.",
  "She is worried about the deadline.",
  "They are proud of their progress.",
  "He is interested in learning design.",
  "We are ready for the interview.",
  "I have to leave now.",
  "She has to attend a workshop.",
  "They have to fix the bug today.",
  "He doesn’t have to work tomorrow.",
  "We don’t have to rush.",
  "I want to improve my pronunciation.",
  "She wants to travel next year.",
  "They want to start a small business.",
  "He doesn’t want to talk about it.",
  "We want to learn something new.",
  "I like watching movies at home.",
  "She enjoys reading before sleep.",
  "They love playing team sports.",
  "He hates waiting in long lines.",
  "We prefer working in the morning.",
  "I will be working tomorrow morning.",
  "She will be traveling next week.",
  "They will be studying tonight.",
  "He will be waiting at the lobby.",
  "We will be discussing the results soon.",
  "I will have finished by 5 PM.",
  "She will have arrived before noon.",
  "They will have completed the course by July.",
  "He will have saved enough money by then.",
  "We will have met the target by Friday.",
  "I will have been working here for two years by June.",
  "She will have been studying English for months by then.",
  "They will have been living here for a year by August.",
  "He will have been practicing daily for weeks by Friday.",
  "We will have been waiting for hours by midnight."
];
