export default [
    // --- Essential Nouns ---
    { indonesian: "rumah", english: "house" },
    { indonesian: "kantor", english: "office" },
    { indonesian: "uang", english: "money" },
    { indonesian: "pekerjaan", english: "job" },
    { indonesian: "kegiatan", english: "activity" },
    { indonesian: "acara", english: "event" },
    { indonesian: "pertemuan", english: "meeting" },
    { indonesian: "janji", english: "promise" },
    { indonesian: "undangan", english: "invitation" },
    { indonesian: "permintaan", english: "request" },
    { indonesian: "penawaran", english: "offer" },
    { indonesian: "kesepakatan", english: "agreement" },
    { indonesian: "kontrak", english: "contract" },
    { indonesian: "dokumen", english: "document" },
    { indonesian: "laporan", english: "report" },
    { indonesian: "proyek", english: "project" },
    { indonesian: "tugas", english: "task" },
    { indonesian: "tanggung jawab", english: "responsibility" },

    { indonesian: "tanggung jawab", english: "responsibility" },
    { indonesian: "kewajiban", english: "obligation" },
    { indonesian: "hak", english: "right" },
    { indonesian: "kesempatan", english: "opportunity" },
    { indonesian: "kemungkinan", english: "possibility" },
    { indonesian: "peluang", english: "chance" },
    { indonesian: "risiko", english: "risk" },
    { indonesian: "tantangan", english: "challenge" },
    { indonesian: "hambatan", english: "obstacle" },
    { indonesian: "kendala", english: "constraint" },
    { indonesian: "usaha", english: "effort" },
    { indonesian: "upaya", english: "attempt" },
    { indonesian: "pencapaian", english: "achievement" },
    { indonesian: "prestasi", english: "accomplishment" },
    { indonesian: "kegagalan", english: "failure" },
    { indonesian: "kesuksesan", english: "success" },

    // --- People & Relationships ---
    { indonesian: "teman", english: "friend" },
    { indonesian: "sahabat", english: "best friend" },
    { indonesian: "kenalan", english: "acquaintance" },
    { indonesian: "tetangga", english: "neighbor" },
    { indonesian: "rekan", english: "colleague" },
    { indonesian: "mitra", english: "partner" },
    { indonesian: "pesaing", english: "competitor" },
    { indonesian: "lawan", english: "opponent" },
    { indonesian: "musuh", english: "enemy" },
    { indonesian: "pengikut", english: "follower" },
    { indonesian: "pemimpin", english: "leader" },
    { indonesian: "bos", english: "boss" },
    { indonesian: "atasan", english: "superior" },
    { indonesian: "bawahan", english: "subordinate" },
    { indonesian: "klien", english: "client" },
    { indonesian: "pelanggan", english: "customer" },
    { indonesian: "konsumen", english: "consumer" },
    { indonesian: "penyedia", english: "provider" },

    { indonesian: "penyedia", english: "provider" },

    // --- Essential Verbs ---
    { indonesian: "pergi", english: "go" },
    { indonesian: "datang", english: "come" },
    { indonesian: "bekerja", english: "work" },
    { indonesian: "belajar", english: "study" },
    { indonesian: "berbicara", english: "speak" },
    { indonesian: "mendengar", english: "hear" },
    { indonesian: "mendengarkan", english: "listen" },
    { indonesian: "melihat", english: "see" },
    { indonesian: "menonton", english: "watch" },
    { indonesian: "membaca", english: "read" },
    { indonesian: "menulis", english: "write" },
    { indonesian: "memahami", english: "comprehend" },
    { indonesian: "menjelaskan", english: "explain" },
    { indonesian: "menggambarkan", english: "describe" },
    { indonesian: "menyebutkan", english: "mention" },
    { indonesian: "memberitahu", english: "inform" },
    { indonesian: "mengumumkan", english: "announce" },
    { indonesian: "menyarankan", english: "suggest" },
    { indonesian: "merekomendasikan", english: "recommend" },
    { indonesian: "mengusulkan", english: "propose" },
    { indonesian: "menawarkan", english: "offer" },
    { indonesian: "menerima", english: "accept" },
    { indonesian: "menolak", english: "reject" },
    { indonesian: "membatalkan", english: "cancel" },
    { indonesian: "menunda", english: "postpone" },
    { indonesian: "melanjutkan", english: "continue" },
    { indonesian: "menghentikan", english: "stop" },
    { indonesian: "memulai", english: "begin" },
    { indonesian: "mengakhiri", english: "end" },
    { indonesian: "menyelesaikan", english: "complete" },
    { indonesian: "mencapai", english: "achieve" },
    { indonesian: "mendapatkan", english: "obtain" },
    { indonesian: "memperoleh", english: "acquire" },
    { indonesian: "kehilangan", english: "lose" },
    { indonesian: "menemukan", english: "discover" },
    { indonesian: "mencari", english: "search" },
    { indonesian: "mengikuti", english: "follow" },
    { indonesian: "memimpin", english: "lead" },
    { indonesian: "mengatur", english: "manage" },
    { indonesian: "mengorganisir", english: "organize" },
    { indonesian: "merencanakan", english: "plan" },
    { indonesian: "mempersiapkan", english: "prepare" },
    { indonesian: "melaksanakan", english: "execute" },
    { indonesian: "menerapkan", english: "implement" },
    { indonesian: "menggunakan", english: "utilize" },
    { indonesian: "memanfaatkan", english: "leverage" },
    { indonesian: "memperbaiki", english: "improve" },
    { indonesian: "meningkatkan", english: "enhance" },
    { indonesian: "mengurangi", english: "reduce" },
    { indonesian: "menurunkan", english: "decrease" },
    { indonesian: "menambah", english: "add" },
    { indonesian: "menghapus", english: "delete" },
    { indonesian: "mengubah", english: "modify" },
    { indonesian: "menyesuaikan", english: "adjust" },
    { indonesian: "membandingkan", english: "compare" },
    { indonesian: "membedakan", english: "distinguish" },
    { indonesian: "mengidentifikasi", english: "identify" },
    { indonesian: "mengenali", english: "recognize" },
    { indonesian: "mempertimbangkan", english: "consider" },
    { indonesian: "mengevaluasi", english: "evaluate" },
    { indonesian: "menilai", english: "assess" },
    { indonesian: "memutuskan", english: "decide" },
    { indonesian: "menentukan", english: "determine" },
    { indonesian: "memilih", english: "choose" },
    { indonesian: "memilah", english: "sort" },

    { indonesian: "memilah", english: "sort" },
    { indonesian: "menikmati", english: "enjoy" },
    { indonesian: "merasakan", english: "feel" },
    { indonesian: "mengalami", english: "experience" },
    { indonesian: "menderita", english: "suffer" },
    { indonesian: "mengharapkan", english: "expect" },
    { indonesian: "berharap", english: "hope" },
    { indonesian: "bermimpi", english: "dream" },
    { indonesian: "khawatir", english: "worry" },
    { indonesian: "peduli", english: "care" },
    { indonesian: "menghargai", english: "appreciate" },
    { indonesian: "menghormati", english: "respect" },
    { indonesian: "mengagumi", english: "admire" },
    { indonesian: "mencintai", english: "love" },
    { indonesian: "membenci", english: "hate" },
    { indonesian: "menyukai", english: "like" },
    { indonesian: "menyesal", english: "regret" },
    { indonesian: "mengingat", english: "recall" },
    { indonesian: "melupakan", english: "forget" },

    // --- Conjunctions & Linking Words ---
    { indonesian: "meskipun", english: "although" },
    { indonesian: "walaupun", english: "even though" },
    { indonesian: "namun", english: "however" },
    { indonesian: "tetapi", english: "but" },
    { indonesian: "sementara", english: "while" },
    { indonesian: "sedangkan", english: "whereas" },
    { indonesian: "selama", english: "during" },
    { indonesian: "ketika", english: "when" },
    { indonesian: "saat", english: "at the time" },
    { indonesian: "sebelum", english: "before" },
    { indonesian: "sesudah", english: "after" },
    { indonesian: "sejak", english: "since" },
    { indonesian: "sampai", english: "until" },
    { indonesian: "karena itu", english: "therefore" },
    { indonesian: "sehingga", english: "so that" },
    { indonesian: "supaya", english: "in order to" },
    { indonesian: "agar", english: "so that" },
    { indonesian: "kalau", english: "if" },
    { indonesian: "seandainya", english: "if only" },
    { indonesian: "seolah-olah", english: "as if" },
    { indonesian: "seakan-akan", english: "as though" },
    { indonesian: "kecuali", english: "except" },
    { indonesian: "selain", english: "besides" },
    { indonesian: "malah", english: "instead" },
    { indonesian: "bahkan", english: "even" },
    { indonesian: "apalagi", english: "moreover" },
    { indonesian: "lagipula", english: "furthermore" },

    // --- Common Phrases & Contractions ---
    { indonesian: "apakah kamu", english: "do you" },
    { indonesian: "apakah dia", english: "does he/she" },
    { indonesian: "apakah mereka", english: "do they" },
    { indonesian: "apa yang", english: "what" },
    { indonesian: "bagaimana jika", english: "what if" },
    { indonesian: "kenapa tidak", english: "why not" },
    { indonesian: "mengapa harus", english: "why should" },
    { indonesian: "ini adalah", english: "this is" },
    { indonesian: "itu adalah", english: "that is" },
    { indonesian: "dia adalah", english: "he/she is" },
    { indonesian: "mereka adalah", english: "they are" },
    { indonesian: "saya adalah", english: "I am" },
    { indonesian: "kami adalah", english: "we are" },
    { indonesian: "kamu adalah", english: "you are" },

    // --- Progressive Forms (being, doing, etc) ---
    { indonesian: "sedang", english: "being" },
    { indonesian: "sedang melakukan", english: "doing" },
    { indonesian: "sedang bekerja", english: "working" },
    { indonesian: "sedang belajar", english: "studying" },
    { indonesian: "sedang makan", english: "eating" },
    { indonesian: "sedang tidur", english: "sleeping" },
    { indonesian: "sedang berbicara", english: "talking" },
    { indonesian: "sedang mendengarkan", english: "listening" },
    { indonesian: "sedang menonton", english: "watching" },
    { indonesian: "sedang membaca", english: "reading" },
    { indonesian: "sedang menulis", english: "writing" },
    { indonesian: "sedang berpikir", english: "thinking" },
    { indonesian: "sedang mencoba", english: "trying" },
    { indonesian: "sedang menunggu", english: "waiting" },
    { indonesian: "sedang mencari", english: "looking for" },
    { indonesian: "sedang datang", english: "coming" },
    { indonesian: "sedang pergi", english: "going" },
    { indonesian: "sedang berlangsung", english: "happening" },
    { indonesian: "sedang berjalan", english: "running" },
    { indonesian: "sedang digunakan", english: "being used" },
    { indonesian: "sedang dibahas", english: "being discussed" },
    { indonesian: "sedang dipertimbangkan", english: "being considered" },

    // --- Past Tense Forms ---
    { indonesian: "telah", english: "have/has" },
    { indonesian: "telah melakukan", english: "have done" },
    { indonesian: "telah selesai", english: "have finished" },
    { indonesian: "telah pergi", english: "have gone" },
    { indonesian: "telah datang", english: "have come" },
    { indonesian: "telah makan", english: "have eaten" },
    { indonesian: "telah bekerja", english: "have worked" },
    { indonesian: "telah belajar", english: "have studied" },
    { indonesian: "telah membaca", english: "have read" },
    { indonesian: "telah menulis", english: "have written" },
    { indonesian: "telah melihat", english: "have seen" },
    { indonesian: "telah mendengar", english: "have heard" },
    { indonesian: "telah mencoba", english: "have tried" },
    { indonesian: "telah berubah", english: "have changed" },
    { indonesian: "pernah", english: "have ever" },
    { indonesian: "pernah melakukan", english: "have done before" },
    { indonesian: "pernah mengalami", english: "have experienced" },
    { indonesian: "baru saja", english: "just" },
    { indonesian: "baru saja selesai", english: "just finished" },
    { indonesian: "baru saja tiba", english: "just arrived" },

    // --- Future Tense Forms ---
    { indonesian: "akan", english: "will" },
    { indonesian: "akan melakukan", english: "will do" },
    { indonesian: "akan pergi", english: "will go" },
    { indonesian: "akan datang", english: "will come" },
    { indonesian: "akan bekerja", english: "will work" },
    { indonesian: "akan belajar", english: "will study" },
    { indonesian: "akan mencoba", english: "will try" },
    { indonesian: "akan memulai", english: "will start" },
    { indonesian: "akan selesai", english: "will finish" },
    { indonesian: "akan berubah", english: "will change" },
    { indonesian: "akan terjadi", english: "will happen" },
    { indonesian: "akan menjadi", english: "will become" },
    { indonesian: "hendak", english: "going to" },
    { indonesian: "hendak pergi", english: "going to go" },
    { indonesian: "hendak melakukan", english: "going to do" },
    { indonesian: "berencana", english: "planning to" },
    { indonesian: "bermaksud", english: "intending to" },

    // --- Modal Verbs & Auxiliaries ---
    { indonesian: "bisa", english: "can" },
    { indonesian: "dapat", english: "able to" },
    { indonesian: "mampu", english: "capable" },
    { indonesian: "harus", english: "must" },
    { indonesian: "perlu", english: "need to" },
    { indonesian: "wajib", english: "have to" },
    { indonesian: "seharusnya", english: "should" },
    { indonesian: "sebaiknya", english: "ought to" },
    { indonesian: "mungkin", english: "might" },
    { indonesian: "barangkali", english: "perhaps" },
    { indonesian: "boleh jadi", english: "may be" },
    { indonesian: "harusnya", english: "supposed to" },
    { indonesian: "mestinya", english: "should have" },
    { indonesian: "seandainya bisa", english: "wish could" },
    { indonesian: "andai bisa", english: "if only could" },

    // --- Conversational Verbs ---
    { indonesian: "merasa", english: "feel" },
    { indonesian: "tampak", english: "seem" },
    { indonesian: "terlihat", english: "appear" },
    { indonesian: "terdengar", english: "sound" },
    { indonesian: "berbau", english: "smell" },
    { indonesian: "terasa", english: "taste" },
    { indonesian: "menjadi", english: "become" },
    { indonesian: "tetap", english: "remain" },
    { indonesian: "tinggal", english: "stay" },
    { indonesian: "berubah", english: "change" },
    { indonesian: "berkembang", english: "develop" },
    { indonesian: "bertumbuh", english: "grow" },
    { indonesian: "meningkat", english: "increase" },
    { indonesian: "menurun", english: "decline" },
    { indonesian: "tumbuh", english: "rise" },
    { indonesian: "jatuh", english: "fall" },
    { indonesian: "naik", english: "rise" },
    { indonesian: "turun", english: "drop" },

    // --- Descriptive Adjectives ---
    { indonesian: "besar", english: "big", category: "Adjectives" },
    { indonesian: "kecil", english: "small", category: "Adjectives" },
    { indonesian: "tinggi", english: "tall", category: "Adjectives" },
    { indonesian: "rendah", english: "short", category: "Adjectives" },
    { indonesian: "panjang", english: "long", category: "Adjectives" },
    { indonesian: "pendek", english: "short", category: "Adjectives" },
    { indonesian: "lebar", english: "wide", category: "Adjectives" },
    { indonesian: "sempit", english: "narrow", category: "Adjectives" },
    { indonesian: "tebal", english: "thick", category: "Adjectives" },
    { indonesian: "tipis", english: "thin", category: "Adjectives" },
    { indonesian: "berat", english: "heavy", category: "Adjectives" },
    { indonesian: "ringan", english: "light", category: "Adjectives" },
    { indonesian: "cepat", english: "fast", category: "Adjectives" },
    { indonesian: "lambat", english: "slow", category: "Adjectives" },
    { indonesian: "panas", english: "hot", category: "Adjectives" },
    { indonesian: "dingin", english: "cold", category: "Adjectives" },
    { indonesian: "hangat", english: "warm", category: "Adjectives" },
    { indonesian: "sejuk", english: "cool", category: "Adjectives" },
    { indonesian: "baik", english: "good", category: "Adjectives" },
    { indonesian: "buruk", english: "bad", category: "Adjectives" },
    { indonesian: "bagus", english: "nice", category: "Adjectives" },
    { indonesian: "jelek", english: "ugly", category: "Adjectives" },
    { indonesian: "cantik", english: "beautiful", category: "Adjectives" },
    { indonesian: "tampan", english: "handsome", category: "Adjectives" },
    { indonesian: "muda", english: "young", category: "Adjectives" },
    { indonesian: "tua", english: "old", category: "Adjectives" },
    { indonesian: "baru", english: "new", category: "Adjectives" },
    { indonesian: "lama", english: "old", category: "Adjectives" },
    { indonesian: "bersih", english: "clean", category: "Adjectives" },
    { indonesian: "kotor", english: "dirty", category: "Adjectives" },
    { indonesian: "terang", english: "bright", category: "Adjectives" },
    { indonesian: "gelap", english: "dark", category: "Adjectives" },
    { indonesian: "keras", english: "hard", category: "Adjectives" },
    { indonesian: "lembut", english: "soft", category: "Adjectives" },
    { indonesian: "kuat", english: "strong", category: "Adjectives" },
    { indonesian: "lemah", english: "weak", category: "Adjectives" },
    { indonesian: "pintar", english: "smart", category: "Adjectives" },
    { indonesian: "bodoh", english: "stupid", category: "Adjectives" },
    { indonesian: "senang", english: "happy", category: "Adjectives" },
    { indonesian: "sedih", english: "sad", category: "Adjectives" },
    { indonesian: "marah", english: "angry", category: "Adjectives" },
    { indonesian: "takut", english: "afraid", category: "Adjectives" },

    // --- Colors ---
    { indonesian: "merah", english: "red", category: "Colors" },
    { indonesian: "biru", english: "blue", category: "Colors" },
    { indonesian: "kuning", english: "yellow", category: "Colors" },
    { indonesian: "hijau", english: "green", category: "Colors" },
    { indonesian: "hitam", english: "black", category: "Colors" },
    { indonesian: "putih", english: "white", category: "Colors" },
    { indonesian: "abu-abu", english: "gray", category: "Colors" },
    { indonesian: "coklat", english: "brown", category: "Colors" },
    { indonesian: "orange", english: "orange", category: "Colors" },
    { indonesian: "ungu", english: "purple", category: "Colors" },
    { indonesian: "pink", english: "pink", category: "Colors" },

    // --- Time ---
    { indonesian: "hari", english: "day", category: "Time" },
    { indonesian: "minggu", english: "week", category: "Time" },
    { indonesian: "bulan", english: "month", category: "Time" },
    { indonesian: "tahun", english: "year", category: "Time" },
    { indonesian: "jam", english: "hour", category: "Time" },
    { indonesian: "menit", english: "minute", category: "Time" },
    { indonesian: "detik", english: "second", category: "Time" },
    { indonesian: "pagi", english: "morning", category: "Time" },
    { indonesian: "siang", english: "noon", category: "Time" },
    { indonesian: "sore", english: "afternoon", category: "Time" },
    { indonesian: "malam", english: "night", category: "Time" },
    { indonesian: "kemarin", english: "yesterday", category: "Time" },
    { indonesian: "hari ini", english: "today", category: "Time" },
    { indonesian: "besok", english: "tomorrow", category: "Time" },
   

    // --- Weather ---
    { indonesian: "cuaca", english: "weather", category: "Weather" },
    { indonesian: "hujan", english: "rain", category: "Weather" },
    { indonesian: "salju", english: "snow", category: "Weather" },
    { indonesian: "angin", english: "wind", category: "Weather" },
    { indonesian: "awan", english: "cloud", category: "Weather" },
    { indonesian: "matahari", english: "sun", category: "Weather" },
    { indonesian: "bulan", english: "moon", category: "Weather" },
    { indonesian: "bintang", english: "star", category: "Weather" },
    { indonesian: "petir", english: "lightning", category: "Weather" },
    { indonesian: "guntur", english: "thunder", category: "Weather" },

    // --- Prepositions ---
    { indonesian: "di", english: "at", category: "Prepositions" },
    { indonesian: "pada", english: "on", category: "Prepositions" },
    { indonesian: "dalam", english: "in", category: "Prepositions" },
    { indonesian: "di bawah", english: "under", category: "Prepositions" },
    { indonesian: "di atas", english: "above", category: "Prepositions" },
    { indonesian: "di depan", english: "in front of", category: "Prepositions" },
    { indonesian: "di belakang", english: "behind", category: "Prepositions" },
    { indonesian: "di samping", english: "beside", category: "Prepositions" },
    { indonesian: "antara", english: "between", category: "Prepositions" },
    { indonesian: "dekat", english: "near", category: "Prepositions" },
    { indonesian: "jauh", english: "far", category: "Prepositions" },

    // --- Question Words ---
    { indonesian: "apa", english: "what", category: "Questions" },
    { indonesian: "siapa", english: "who", category: "Questions" },
    { indonesian: "dimana", english: "where", category: "Questions" },
    { indonesian: "kapan", english: "when", category: "Questions" },
    { indonesian: "mengapa", english: "why", category: "Questions" },
    { indonesian: "bagaimana", english: "how", category: "Questions" },
    { indonesian: "berapa", english: "how much/many", category: "Questions" },

    // --- Common Expressions ---
    { indonesian: "ya", english: "yes", category: "Common" },
    { indonesian: "tidak", english: "no", category: "Common" },
    { indonesian: "tolong", english: "please", category: "Common" },
    { indonesian: "terima kasih", english: "thank you", category: "Common" },
    { indonesian: "maaf", english: "sorry", category: "Common" },
    { indonesian: "permisi", english: "excuse me", category: "Common" },
    { indonesian: "halo", english: "hello", category: "Common" },
    { indonesian: "selamat tinggal", english: "goodbye", category: "Common" },
    { indonesian: "selamat pagi", english: "good morning", category: "Common" },
    { indonesian: "selamat siang", english: "good afternoon", category: "Common" },
    { indonesian: "selamat malam", english: "good evening", category: "Common" },
    { indonesian: "selamat tidur", english: "good night", category: "Common" },

    // --- Technology ---
    { indonesian: "komputer", english: "computer", category: "Technology" },
    { indonesian: "laptop", english: "laptop", category: "Technology" },
    { indonesian: "internet", english: "internet", category: "Technology" },
    { indonesian: "website", english: "website", category: "Technology" },
    { indonesian: "email", english: "email", category: "Technology" },
    { indonesian: "aplikasi", english: "application", category: "Technology" },
    { indonesian: "program", english: "program", category: "Technology" },
    { indonesian: "data", english: "data", category: "Technology" },
    { indonesian: "file", english: "file", category: "Technology" },
    { indonesian: "folder", english: "folder", category: "Technology" },
    { indonesian: "printer", english: "printer", category: "Technology" },
    { indonesian: "scanner", english: "scanner", category: "Technology" },
    { indonesian: "mouse", english: "mouse", category: "Technology" },
    { indonesian: "keyboard", english: "keyboard", category: "Technology" },
    { indonesian: "layar", english: "screen", category: "Technology" },

    // --- Transportation ---
    { indonesian: "mobil", english: "car", category: "Transportation" },
    { indonesian: "motor", english: "motorcycle", category: "Transportation" },
    { indonesian: "sepeda", english: "bicycle", category: "Transportation" },
    { indonesian: "bus", english: "bus", category: "Transportation" },
    { indonesian: "kereta", english: "train", category: "Transportation" },
    { indonesian: "pesawat", english: "airplane", category: "Transportation" },
    { indonesian: "kapal", english: "ship", category: "Transportation" },
    { indonesian: "perahu", english: "boat", category: "Transportation" },
    { indonesian: "taksi", english: "taxi", category: "Transportation" },

    // --- School Subjects ---
    { indonesian: "matematika", english: "mathematics", category: "School" },
    { indonesian: "sains", english: "science", category: "School" },
    { indonesian: "bahasa Inggris", english: "English", category: "School" },
    { indonesian: "sejarah", english: "history", category: "School" },
    { indonesian: "geografi", english: "geography", category: "School" },
    { indonesian: "seni", english: "art", category: "School" },
    { indonesian: "musik", english: "music", category: "School" },
    { indonesian: "olahraga", english: "sports", category: "School" },
    { indonesian: "fisika", english: "physics", category: "School" },
    { indonesian: "kimia", english: "chemistry", category: "School" },
    { indonesian: "biologi", english: "biology", category: "School" },

    // --- Emotions & Feelings ---
    { indonesian: "senang", english: "happy", category: "Emotions" },
    { indonesian: "sedih", english: "sad", category: "Emotions" },
    { indonesian: "marah", english: "angry", category: "Emotions" },
    { indonesian: "takut", english: "scared", category: "Emotions" },
    { indonesian: "cemas", english: "anxious", category: "Emotions" },
    { indonesian: "bosan", english: "bored", category: "Emotions" },
    { indonesian: "lelah", english: "tired", category: "Emotions" },
    { indonesian: "sakit", english: "sick", category: "Emotions" },
    { indonesian: "sehat", english: "healthy", category: "Emotions" },
    { indonesian: "kaget", english: "surprised", category: "Emotions" },
    { indonesian: "bangga", english: "proud", category: "Emotions" },
    { indonesian: "malu", english: "shy", category: "Emotions" },
    { indonesian: "cinta", english: "love", category: "Emotions" },
    { indonesian: "benci", english: "hate", category: "Emotions" },

    // --- Professions ---
    { indonesian: "dokter", english: "doctor", category: "Professions" },
    { indonesian: "guru", english: "teacher", category: "Professions" },
    { indonesian: "insinyur", english: "engineer", category: "Professions" },
    { indonesian: "perawat", english: "nurse", category: "Professions" },
    { indonesian: "pengacara", english: "lawyer", category: "Professions" },
    { indonesian: "akuntan", english: "accountant", category: "Professions" },
    { indonesian: "arsitek", english: "architect", category: "Professions" },
    { indonesian: "seniman", english: "artist", category: "Professions" },
    { indonesian: "musisi", english: "musician", category: "Professions" },
    { indonesian: "penulis", english: "writer", category: "Professions" },
    { indonesian: "jurnalis", english: "journalist", category: "Professions" },
    { indonesian: "fotografer", english: "photographer", category: "Professions" },
    { indonesian: "koki", english: "chef", category: "Professions" },
    { indonesian: "polisi", english: "police officer", category: "Professions" },
    { indonesian: "tentara", english: "soldier", category: "Professions" },

    // --- Sports & Activities ---
    { indonesian: "sepak bola", english: "football/soccer", category: "Sports" },
    { indonesian: "basket", english: "basketball", category: "Sports" },
    { indonesian: "voli", english: "volleyball", category: "Sports" },
    { indonesian: "tenis", english: "tennis", category: "Sports" },
    { indonesian: "renang", english: "swimming", category: "Sports" },
    { indonesian: "lari", english: "running", category: "Sports" },
    { indonesian: "bersepeda", english: "cycling", category: "Sports" },
    { indonesian: "yoga", english: "yoga", category: "Sports" },
    { indonesian: "berenang", english: "swim", category: "Sports" },
    { indonesian: "memancing", english: "fishing", category: "Sports" },

    // --- Materials ---
    { indonesian: "kayu", english: "wood", category: "Materials" },
    { indonesian: "besi", english: "iron", category: "Materials" },
    { indonesian: "baja", english: "steel", category: "Materials" },
    { indonesian: "kaca", english: "glass", category: "Materials" },
    { indonesian: "plastik", english: "plastic", category: "Materials" },
    { indonesian: "kertas", english: "paper", category: "Materials" },
    { indonesian: "kain", english: "cloth", category: "Materials" },
    { indonesian: "kulit", english: "leather", category: "Materials" },
    { indonesian: "batu", english: "stone", category: "Materials" },
    { indonesian: "emas", english: "gold", category: "Materials" },
    { indonesian: "perak", english: "silver", category: "Materials" },

    // --- Directions ---
    { indonesian: "utara", english: "north", category: "Directions" },
    { indonesian: "selatan", english: "south", category: "Directions" },
    { indonesian: "timur", english: "east", category: "Directions" },
    { indonesian: "barat", english: "west", category: "Directions" },
    { indonesian: "kiri", english: "left", category: "Directions" },
    { indonesian: "kanan", english: "right", category: "Directions" },
    { indonesian: "lurus", english: "straight", category: "Directions" },

    // --- Additional Common Words ---
    { indonesian: "semua", english: "all", category: "Common" },
    { indonesian: "beberapa", english: "some", category: "Common" },
    { indonesian: "banyak", english: "many", category: "Common" },
    { indonesian: "sedikit", english: "few", category: "Common" },
    { indonesian: "sangat", english: "very", category: "Common" },
    { indonesian: "terlalu", english: "too", category: "Common" },
    { indonesian: "juga", english: "also", category: "Common" },
    { indonesian: "tapi", english: "but", category: "Common" },
    { indonesian: "atau", english: "or", category: "Common" },
    { indonesian: "dan", english: "and", category: "Common" },
    { indonesian: "karena", english: "because", category: "Common" },
    { indonesian: "jika", english: "if", category: "Common" },
    { indonesian: "maka", english: "then", category: "Common" },
    { indonesian: "sekarang", english: "now", category: "Common" },
    { indonesian: "nanti", english: "later", category: "Common" },
    { indonesian: "selalu", english: "always", category: "Common" },
    { indonesian: "sering", english: "often", category: "Common" },
    { indonesian: "kadang", english: "sometimes", category: "Common" },
    { indonesian: "jarang", english: "rarely", category: "Common" },
    { indonesian: "tidak pernah", english: "never", category: "Common" },

    // --- Conversational & Daily Use Words ---
    { indonesian: "dengan", english: "with", category: "Common" },
    { indonesian: "untuk", english: "for", category: "Common" },
    { indonesian: "dari", english: "from", category: "Common" },
    { indonesian: "ke", english: "to", category: "Common" },
    { indonesian: "di sini", english: "here", category: "Common" },
    { indonesian: "di sana", english: "there", category: "Common" },
    { indonesian: "ini", english: "this", category: "Common" },
    { indonesian: "itu", english: "that", category: "Common" },
    { indonesian: "saya", english: "I", category: "Common" },
    { indonesian: "kamu", english: "you", category: "Common" },
    { indonesian: "dia", english: "he/she", category: "Common" },
    { indonesian: "kami", english: "we", category: "Common" },
    { indonesian: "mereka", english: "they", category: "Common" },
    { indonesian: "milik saya", english: "mine", category: "Common" },
    { indonesian: "milik kamu", english: "yours", category: "Common" },
    { indonesian: "bisa", english: "can", category: "Common" },
    { indonesian: "tidak bisa", english: "cannot", category: "Common" },
    { indonesian: "harus", english: "must", category: "Common" },
    { indonesian: "ingin", english: "want", category: "Common" },
    { indonesian: "perlu", english: "need", category: "Common" },
    { indonesian: "suka", english: "like", category: "Common" },
    { indonesian: "cinta", english: "love", category: "Common" },
    { indonesian: "tahu", english: "know", category: "Common" },
    { indonesian: "tidak tahu", english: "don't know", category: "Common" },
    { indonesian: "mengerti", english: "understand", category: "Common" },
    { indonesian: "tidak mengerti", english: "don't understand", category: "Common" },
    { indonesian: "pikir", english: "think", category: "Common" },
    { indonesian: "percaya", english: "believe", category: "Common" },
    { indonesian: "ingat", english: "remember", category: "Common" },
    { indonesian: "lupa", english: "forget", category: "Common" },
    { indonesian: "tunggu", english: "wait", category: "Common" },
    { indonesian: "lihat", english: "see/look", category: "Common" },
    { indonesian: "coba", english: "try", category: "Common" },
    { indonesian: "pakai", english: "use", category: "Common" },
    { indonesian: "butuh", english: "need", category: "Common" },
    { indonesian: "punya", english: "have", category: "Common" },
    { indonesian: "ada", english: "there is/are", category: "Common" },
    { indonesian: "tidak ada", english: "there isn't/aren't", category: "Common" },
    { indonesian: "boleh", english: "may/allowed", category: "Common" },
    { indonesian: "tidak boleh", english: "not allowed", category: "Common" },
    { indonesian: "mau", english: "want", category: "Common" },
    { indonesian: "tidak mau", english: "don't want", category: "Common" },
    { indonesian: "sudah", english: "already", category: "Common" },
    { indonesian: "belum", english: "not yet", category: "Common" },
    { indonesian: "masih", english: "still", category: "Common" },
    { indonesian: "lagi", english: "again", category: "Common" },
    { indonesian: "lebih", english: "more", category: "Common" },
    { indonesian: "kurang", english: "less", category: "Common" },
    { indonesian: "sama", english: "same", category: "Common" },
    { indonesian: "beda", english: "different", category: "Common" },
    { indonesian: "lain", english: "other", category: "Common" },
    { indonesian: "sendiri", english: "alone", category: "Common" },
    { indonesian: "bersama", english: "together", category: "Common" },
    { indonesian: "siap", english: "ready", category: "Common" },
    { indonesian: "selesai", english: "finished", category: "Common" },
    { indonesian: "mulai", english: "start", category: "Common" },
    { indonesian: "berhenti", english: "stop", category: "Common" },
    { indonesian: "cepat", english: "quick/fast", category: "Common" },
    { indonesian: "pelan", english: "slow", category: "Common" },
    { indonesian: "baik-baik saja", english: "fine", category: "Common" },
    { indonesian: "tidak apa-apa", english: "it's okay", category: "Common" },
    { indonesian: "tenang", english: "calm", category: "Common" },
    { indonesian: "ramai", english: "crowded", category: "Common" },
    { indonesian: "sepi", english: "quiet", category: "Common" },
    { indonesian: "aman", english: "safe", category: "Common" },
    { indonesian: "bahaya", english: "dangerous", category: "Common" },
    { indonesian: "mudah", english: "easy", category: "Common" },
    { indonesian: "sulit", english: "difficult", category: "Common" },
    { indonesian: "penting", english: "important", category: "Common" },
    { indonesian: "biasa", english: "normal", category: "Common" },
    { indonesian: "khusus", english: "special", category: "Common" },
    { indonesian: "benar", english: "correct/right", category: "Common" },
    { indonesian: "salah", english: "wrong", category: "Common" },
    { indonesian: "betul", english: "true", category: "Common" },
    { indonesian: "bohong", english: "lie", category: "Common" },

    // --- More Conversational Verbs ---
    { indonesian: "bilang", english: "say/tell", category: "Verbs" },
    { indonesian: "tanya", english: "ask", category: "Verbs" },
    { indonesian: "jawab", english: "answer", category: "Verbs" },
    { indonesian: "cerita", english: "tell a story", category: "Verbs" },
    { indonesian: "tertawa", english: "laugh", category: "Verbs" },
    { indonesian: "menangis", english: "cry", category: "Verbs" },
    { indonesian: "senyum", english: "smile", category: "Verbs" },
    { indonesian: "panggil", english: "call", category: "Verbs" },
    { indonesian: "kirim", english: "send", category: "Verbs" },
    { indonesian: "terima", english: "receive", category: "Verbs" },
    { indonesian: "cari", english: "search/look for", category: "Verbs" },
    { indonesian: "temukan", english: "find", category: "Verbs" },
    { indonesian: "hilang", english: "lose/lost", category: "Verbs" },
    { indonesian: "simpan", english: "save/keep", category: "Verbs" },
    { indonesian: "buang", english: "throw away", category: "Verbs" },
    { indonesian: "ambil", english: "take/get", category: "Verbs" },
    { indonesian: "taruh", english: "put", category: "Verbs" },
    { indonesian: "letakkan", english: "place", category: "Verbs" },
    { indonesian: "angkat", english: "lift/pick up", category: "Verbs" },
    { indonesian: "jatuh", english: "fall", category: "Verbs" },
    { indonesian: "naik", english: "go up/ride", category: "Verbs" },
    { indonesian: "turun", english: "go down/get off", category: "Verbs" },
    { indonesian: "masuk", english: "enter", category: "Verbs" },
    { indonesian: "keluar", english: "exit/go out", category: "Verbs" },
    { indonesian: "kembali", english: "return", category: "Verbs" },
    { indonesian: "pulang", english: "go home", category: "Verbs" },
    { indonesian: "tinggal", english: "live/stay", category: "Verbs" },
    { indonesian: "pindah", english: "move", category: "Verbs" },
    { indonesian: "ganti", english: "change", category: "Verbs" },
    { indonesian: "bantu", english: "help", category: "Verbs" },
    { indonesian: "tolong", english: "help/please", category: "Verbs" },
    { indonesian: "ajak", english: "invite", category: "Verbs" },
    { indonesian: "ikut", english: "follow/join", category: "Verbs" },
    { indonesian: "tinggalkan", english: "leave", category: "Verbs" },
    { indonesian: "sentuh", english: "touch", category: "Verbs" },
    { indonesian: "pegang", english: "hold", category: "Verbs" },
    { indonesian: "lepas", english: "release", category: "Verbs" },
    { indonesian: "potong", english: "cut", category: "Verbs" },
    { indonesian: "pecah", english: "break", category: "Verbs" },
    { indonesian: "rusak", english: "broken/damaged", category: "Verbs" },
    { indonesian: "perbaiki", english: "fix/repair", category: "Verbs" },
    { indonesian: "buat", english: "make/create", category: "Verbs" },
    { indonesian: "bangun", english: "build", category: "Verbs" },
    { indonesian: "hancurkan", english: "destroy", category: "Verbs" },

    // --- More Useful Nouns ---
    { indonesian: "waktu", english: "time", category: "Nouns" },
    { indonesian: "tempat", english: "place", category: "Nouns" },
    { indonesian: "orang", english: "person/people", category: "Nouns" },
    { indonesian: "hal", english: "thing", category: "Nouns" },
    { indonesian: "masalah", english: "problem", category: "Nouns" },
    { indonesian: "solusi", english: "solution", category: "Nouns" },
    { indonesian: "pertanyaan", english: "question", category: "Nouns" },
    { indonesian: "jawaban", english: "answer", category: "Nouns" },
    { indonesian: "nama", english: "name", category: "Nouns" },
    { indonesian: "umur", english: "age", category: "Nouns" },
    { indonesian: "alamat", english: "address", category: "Nouns" },
    { indonesian: "nomor", english: "number", category: "Nouns" },
    { indonesian: "harga", english: "price", category: "Nouns" },
    { indonesian: "biaya", english: "cost", category: "Nouns" },
    { indonesian: "pekerjaan", english: "job/work", category: "Nouns" },
    { indonesian: "hobi", english: "hobby", category: "Nouns" },
    { indonesian: "kegiatan", english: "activity", category: "Nouns" },
    { indonesian: "rencana", english: "plan", category: "Nouns" },
    { indonesian: "mimpi", english: "dream", category: "Nouns" },
    { indonesian: "harapan", english: "hope", category: "Nouns" },
    { indonesian: "pikiran", english: "thought", category: "Nouns" },
    { indonesian: "perasaan", english: "feeling", category: "Nouns" },
    { indonesian: "kehidupan", english: "life", category: "Nouns" },
    { indonesian: "kematian", english: "death", category: "Nouns" },
    { indonesian: "awal", english: "beginning", category: "Nouns" },
    { indonesian: "akhir", english: "end", category: "Nouns" },
    { indonesian: "kesempatan", english: "opportunity", category: "Nouns" },
    { indonesian: "keberuntungan", english: "luck", category: "Nouns" },
    { indonesian: "nasib", english: "fate", category: "Nouns" },
    { indonesian: "alasan", english: "reason", category: "Nouns" },
    { indonesian: "tujuan", english: "purpose/goal", category: "Nouns" },
    { indonesian: "cara", english: "way/method", category: "Nouns" },
    { indonesian: "hasil", english: "result", category: "Nouns" },
    { indonesian: "keputusan", english: "decision", category: "Nouns" },
    { indonesian: "pilihan", english: "choice", category: "Nouns" },
    { indonesian: "kesalahan", english: "mistake", category: "Nouns" },
    { indonesian: "kebenaran", english: "truth", category: "Nouns" },
    { indonesian: "rahasia", english: "secret", category: "Nouns" },
    { indonesian: "informasi", english: "information", category: "Nouns" },
    { indonesian: "berita", english: "news", category: "Nouns" },
    { indonesian: "cerita", english: "story", category: "Nouns" },
    { indonesian: "pengalaman", english: "experience", category: "Nouns" },
    { indonesian: "pengetahuan", english: "knowledge", category: "Nouns" },
    { indonesian: "kemampuan", english: "ability", category: "Nouns" },
    { indonesian: "kekuatan", english: "strength/power", category: "Nouns" },
    { indonesian: "kelemahan", english: "weakness", category: "Nouns" },

    // --- More Adjectives for Conversation ---
    { indonesian: "sibuk", english: "busy", category: "Adjectives" },
    { indonesian: "malas", english: "lazy", category: "Adjectives" },
    { indonesian: "rajin", english: "diligent", category: "Adjectives" },
    { indonesian: "sabar", english: "patient", category: "Adjectives" },
    { indonesian: "ramah", english: "friendly", category: "Adjectives" },
    { indonesian: "jahat", english: "evil/mean", category: "Adjectives" },
    { indonesian: "baik hati", english: "kind", category: "Adjectives" },
    { indonesian: "jujur", english: "honest", category: "Adjectives" },
    { indonesian: "lucu", english: "funny", category: "Adjectives" },
    { indonesian: "serius", english: "serious", category: "Adjectives" },
    { indonesian: "asik", english: "fun/cool", category: "Adjectives" },
    { indonesian: "membosankan", english: "boring", category: "Adjectives" },
    { indonesian: "menarik", english: "interesting", category: "Adjectives" },
    { indonesian: "aneh", english: "strange", category: "Adjectives" },
    { indonesian: "normal", english: "normal", category: "Adjectives" },
    { indonesian: "keren", english: "cool/awesome", category: "Adjectives" },
    { indonesian: "sempurna", english: "perfect", category: "Adjectives" },
    { indonesian: "lengkap", english: "complete", category: "Adjectives" },
    { indonesian: "kosong", english: "empty", category: "Adjectives" },
    { indonesian: "penuh", english: "full", category: "Adjectives" },
    { indonesian: "gratis", english: "free", category: "Adjectives" },
    { indonesian: "mahal", english: "expensive", category: "Adjectives" },
    { indonesian: "murah", english: "cheap", category: "Adjectives" },
    { indonesian: "kaya", english: "rich", category: "Adjectives" },
    { indonesian: "miskin", english: "poor", category: "Adjectives" },
    { indonesian: "ramai", english: "busy/crowded", category: "Adjectives" },
    { indonesian: "sunyi", english: "silent", category: "Adjectives" },
    { indonesian: "ribut", english: "noisy", category: "Adjectives" },
    { indonesian: "nyaman", english: "comfortable", category: "Adjectives" },
    { indonesian: "enak", english: "delicious/nice", category: "Adjectives" },
    { indonesian: "pahit", english: "bitter", category: "Adjectives" },
    { indonesian: "manis", english: "sweet", category: "Adjectives" },
    { indonesian: "asin", english: "salty", category: "Adjectives" },
    { indonesian: "asam", english: "sour", category: "Adjectives" },
    { indonesian: "pedas", english: "spicy", category: "Adjectives" },
    { indonesian: "segar", english: "fresh", category: "Adjectives" },
    { indonesian: "basi", english: "stale", category: "Adjectives" },
    { indonesian: "basah", english: "wet", category: "Adjectives" },
    { indonesian: "kering", english: "dry", category: "Adjectives" },

    // --- Common Phrases for Conversations ---
    { indonesian: "apa kabar", english: "how are you", category: "Phrases" },
    { indonesian: "baik-baik saja", english: "I'm fine", category: "Phrases" },
    { indonesian: "sampai jumpa", english: "see you", category: "Phrases" },
    { indonesian: "sampai nanti", english: "see you later", category: "Phrases" },
    { indonesian: "sama-sama", english: "you're welcome", category: "Phrases" },
    { indonesian: "tidak masalah", english: "no problem", category: "Phrases" },
    { indonesian: "tentu saja", english: "of course", category: "Phrases" },
    { indonesian: "mungkin", english: "maybe", category: "Phrases" },
    { indonesian: "pasti", english: "definitely", category: "Phrases" },
    { indonesian: "semoga", english: "hopefully", category: "Phrases" },
    { indonesian: "selamat", english: "congratulations", category: "Phrases" },
    { indonesian: "semangat", english: "keep spirit/cheer up", category: "Phrases" },
    { indonesian: "hati-hati", english: "be careful", category: "Phrases" },
    { indonesian: "pelan-pelan", english: "slowly/take it easy", category: "Phrases" },
    { indonesian: "santai", english: "relax", category: "Phrases" },
    { indonesian: "tidak apa-apa", english: "it's okay/no worries", category: "Phrases" },
    { indonesian: "biar saja", english: "let it be", category: "Phrases" },
    { indonesian: "terserah", english: "up to you", category: "Phrases" },
    { indonesian: "sepertinya", english: "it seems", category: "Phrases" },
    { indonesian: "mungkin saja", english: "it's possible", category: "Phrases" },

    // --- Light Talk / Casual Conversation ---
    { indonesian: "ngomong-ngomong", english: "by the way" },
    { indonesian: "eh ya", english: "oh yeah" },
    { indonesian: "apa aja", english: "whatever" },
    { indonesian: "terserah kamu", english: "up to you" },
    { indonesian: "kayaknya", english: "kind of" },
    { indonesian: "agak", english: "sort of" },
    { indonesian: "sebenarnya", english: "actually" },
    { indonesian: "pada dasarnya", english: "basically" },
    { indonesian: "secara harfiah", english: "literally" },
    { indonesian: "jelas", english: "obviously" },
    { indonesian: "pasti dong", english: "definitely" },
    { indonesian: "seperti", english: "like" },
    { indonesian: "gitu deh", english: "you know" },
    { indonesian: "maksud saya", english: "I mean" },
    { indonesian: "kan", english: "right" },
    { indonesian: "iya kan", english: "isn't it" },
    { indonesian: "begitu", english: "so" },
    { indonesian: "nah", english: "well" },
    { indonesian: "oke deh", english: "okay then" },
    { indonesian: "baiklah", english: "alright" },
    { indonesian: "gapapa", english: "no worries" },
    { indonesian: "santai aja", english: "take it easy" },
    { indonesian: "cuek aja", english: "just ignore it" },
    { indonesian: "biasa aja", english: "nothing special" },
    { indonesian: "lumayan", english: "pretty good" },
    { indonesian: "cukup", english: "quite" },
    { indonesian: "cukup bagus", english: "pretty nice" },
    { indonesian: "biasa saja", english: "so-so" },
    { indonesian: "masa sih", english: "really" },
    { indonesian: "serius", english: "seriously" },
    { indonesian: "beneran", english: "for real" },
    { indonesian: "nggak kok", english: "no way" },
    { indonesian: "masa", english: "come on" },
    { indonesian: "gimana", english: "how about" },
    { indonesian: "bagaimana kalau", english: "what about" },

    // --- Serious Talk ---
    { indonesian: "sejujurnya", english: "honestly" },
    { indonesian: "terus terang", english: "frankly" },
    { indonesian: "jujur saja", english: "to be honest" },
    { indonesian: "kenyataannya", english: "in reality" },
    { indonesian: "pada kenyataannya", english: "actually" },
    { indonesian: "sebenarnya masalahnya", english: "the real issue is" },
    { indonesian: "intinya", english: "the point is" },
    { indonesian: "yang penting", english: "what matters is" },
    { indonesian: "hal yang penting", english: "important thing" },
    { indonesian: "masalah serius", english: "serious matter" },
    { indonesian: "perlu dibahas", english: "needs to be discussed" },
    { indonesian: "perlu dipertimbangkan", english: "worth considering" },
    { indonesian: "harus diperhatikan", english: "must pay attention" },
    { indonesian: "perhatian utama", english: "main concern" },
    { indonesian: "fokus utama", english: "main focus" },
    { indonesian: "prioritas", english: "priority" },
    { indonesian: "mendesak", english: "urgent" },
    { indonesian: "krusial", english: "crucial" },
    { indonesian: "sangat penting", english: "very important" },
    { indonesian: "tidak bisa diabaikan", english: "cannot be ignored" },
    { indonesian: "perlu dipahami", english: "need to understand" },
    { indonesian: "harus diakui", english: "must admit" },
    { indonesian: "tidak bisa dipungkiri", english: "cannot deny" },
    { indonesian: "kenyataannya adalah", english: "the fact is" },
    { indonesian: "masalahnya adalah", english: "the problem is" },
    { indonesian: "pertanyaannya adalah", english: "the question is" },

    // --- Self Talk / Personal Expression ---
    { indonesian: "saya sendiri", english: "myself" },
    { indonesian: "diri saya", english: "my self" },
    { indonesian: "secara pribadi", english: "personally" },
    { indonesian: "menurut saya", english: "in my opinion" },
    { indonesian: "pendapat saya", english: "my opinion" },
    { indonesian: "saya rasa", english: "I think" },
    { indonesian: "saya yakin", english: "I believe" },
    { indonesian: "saya merasa", english: "I feel" },
    { indonesian: "rasanya", english: "I feel like" },
    { indonesian: "sepertinya saya", english: "I seem to" },
    { indonesian: "saya cenderung", english: "I tend to" },
    { indonesian: "biasanya saya", english: "I usually" },
    { indonesian: "kebiasaan saya", english: "my habit" },
    { indonesian: "cara saya", english: "my way" },
    { indonesian: "gaya saya", english: "my style" },
    { indonesian: "minat saya", english: "my interest" },
    { indonesian: "passion saya", english: "my passion" },
    { indonesian: "impian saya", english: "my dream" },
    { indonesian: "tujuan saya", english: "my goal" },
    { indonesian: "harapan saya", english: "my hope" },
    { indonesian: "keinginan saya", english: "my desire" },
    { indonesian: "kekhawatiran saya", english: "my concern" },
    { indonesian: "ketakutan saya", english: "my fear" },
    { indonesian: "masalah saya", english: "my problem" },
    { indonesian: "tantangan saya", english: "my challenge" },

    // --- Telling Stories / Past Experiences ---
    { indonesian: "dulu", english: "used to" },
    { indonesian: "dahulu kala", english: "once upon a time" },
    { indonesian: "waktu itu", english: "at that time" },
    { indonesian: "saat itu", english: "back then" },
    { indonesian: "di masa lalu", english: "in the past" },
    { indonesian: "beberapa waktu lalu", english: "some time ago" },
    { indonesian: "tempo hari", english: "the other day" },
    { indonesian: "kemarin dulu", english: "previously" },
    { indonesian: "saya dulu", english: "I used to" },
    { indonesian: "dulu saya pernah", english: "I once" },
    { indonesian: "suatu hari", english: "one day" },
    { indonesian: "suatu ketika", english: "once" },
    { indonesian: "tiba-tiba", english: "suddenly" },
    { indonesian: "kemudian", english: "then" },
    { indonesian: "lalu", english: "and then" },
    { indonesian: "setelah itu", english: "after that" },
    { indonesian: "akhirnya", english: "finally" },
    { indonesian: "pada akhirnya", english: "in the end" },
    { indonesian: "singkat cerita", english: "long story short" },
    { indonesian: "intinya", english: "basically" },
    { indonesian: "pokoknya", english: "anyway" },
    { indonesian: "yang jelas", english: "clearly" },
    { indonesian: "saya ingat", english: "I remember" },
    { indonesian: "kalau tidak salah", english: "if I'm not mistaken" },
    { indonesian: "setahu saya", english: "as far as I know" },
    { indonesian: "pengalaman saya", english: "my experience" },
    { indonesian: "cerita saya", english: "my story" },
    { indonesian: "kejadian yang", english: "what happened" },
    { indonesian: "yang terjadi adalah", english: "what happened was" },

    // --- Common Conversational Fillers ---
    { indonesian: "ya tau lah", english: "you know" },
    { indonesian: "gitu loh", english: "like that" },
    { indonesian: "begitu lah", english: "something like that" },
    { indonesian: "kurang lebih", english: "more or less" },
    { indonesian: "kira-kira", english: "approximately" },
    { indonesian: "sekitar", english: "around" },
    { indonesian: "entahlah", english: "I don't know" },
    { indonesian: "ntah ya", english: "dunno" },
    { indonesian: "siapa tau", english: "who knows" },
    { indonesian: "bisa jadi", english: "could be" },
    { indonesian: "mungkin begitu", english: "maybe so" },
    { indonesian: "kayaknya gitu", english: "seems like it" },
    { indonesian: "kalau menurut saya", english: "if you ask me" },
    { indonesian: "sejauh ini", english: "so far" },
    { indonesian: "sampai sekarang", english: "until now" },
    { indonesian: "untuk saat ini", english: "for now" },
    { indonesian: "sementara ini", english: "at the moment" },
    { indonesian: "belakangan ini", english: "lately" },
    { indonesian: "akhir-akhir ini", english: "recently" },
    { indonesian: "sekarang ini", english: "nowadays" },

    // --- Reaction Words ---
    { indonesian: "wah", english: "wow" },
    { indonesian: "waduh", english: "oh no" },
    { indonesian: "astaga", english: "oh my god" },
    { indonesian: "ya ampun", english: "oh my" },
    { indonesian: "aduh", english: "ouch" },
    { indonesian: "hah", english: "huh" },
    { indonesian: "eh", english: "hey" },
    { indonesian: "kok bisa", english: "how come" },
    { indonesian: "masa iya", english: "really" },
    { indonesian: "benarkah", english: "is that so" },
    { indonesian: "sungguh", english: "truly" },
    { indonesian: "hebat", english: "amazing" },
    { indonesian: "luar biasa", english: "incredible" },
    { indonesian: "menakjubkan", english: "wonderful" },
    { indonesian: "mengejutkan", english: "surprising" },
    { indonesian: "menyedihkan", english: "sad" },
    { indonesian: "menjengkelkan", english: "annoying" },
    { indonesian: "mengecewakan", english: "disappointing" },
    { indonesian: "melegakan", english: "relieving" },

    // --- Agreement & Disagreement ---
    { indonesian: "setuju", english: "agree" },
    { indonesian: "sependapat", english: "same opinion" },
    { indonesian: "sepakat", english: "in agreement" },
    { indonesian: "tidak setuju", english: "disagree" },
    { indonesian: "beda pendapat", english: "different opinion" },
    { indonesian: "menurut saya tidak", english: "I don't think so" },
    { indonesian: "saya rasa tidak", english: "I think not" },
    { indonesian: "mungkin ya", english: "maybe yes" },
    { indonesian: "mungkin tidak", english: "maybe not" },
    { indonesian: "bisa jadi benar", english: "could be right" },
    { indonesian: "belum tentu", english: "not necessarily" },
    { indonesian: "tergantung", english: "it depends" },
    { indonesian: "tergantung situasi", english: "depends on the situation" },
    { indonesian: "relatif", english: "relative" },
    { indonesian: "kontekstual", english: "contextual" },

    // --- Emphasis & Intensifiers ---
    { indonesian: "sangat sekali", english: "very much" },
    { indonesian: "benar-benar", english: "really" },
    { indonesian: "sungguh-sungguh", english: "truly" },
    { indonesian: "amat sangat", english: "extremely" },
    { indonesian: "luar biasa", english: "incredibly" },
    { indonesian: "super", english: "super" },
    { indonesian: "banget", english: "very" },
    { indonesian: "sekali", english: "so much" },
    { indonesian: "betul-betul", english: "absolutely" },
    { indonesian: "sama sekali", english: "at all" },
    { indonesian: "sama sekali tidak", english: "not at all" },
    { indonesian: "sedikit pun tidak", english: "not even a bit" },
    { indonesian: "hampir tidak", english: "hardly" },
    { indonesian: "nyaris tidak", english: "barely" },
    { indonesian: "jarang sekali", english: "very rarely" },
    { indonesian: "hampir selalu", english: "almost always" },
    { indonesian: "kebanyakan", english: "mostly" },
    { indonesian: "umumnya", english: "generally" },
    { indonesian: "biasanya begitu", english: "usually so" },
    { indonesian: "rata-rata", english: "on average" },

    // --- Gen Z & Casual Slang ---
    { indonesian: "semacam", english: "kind of" },
    { indonesian: "agak-agak", english: "kinda" },
    { indonesian: "semacam itu", english: "sorta" },
    { indonesian: "secara harfiah", english: "literally" },
    { indonesian: "vibes", english: "vibe" },
    { indonesian: "suasana", english: "vibe" },
    { indonesian: "getaran", english: "energy" },
    { indonesian: "toxic", english: "toxic" },
    { indonesian: "beracun", english: "toxic" },
    { indonesian: "salty", english: "salty" },
    { indonesian: "kesal", english: "salty" },
    { indonesian: "pamer", english: "flex" },
    { indonesian: "bohong", english: "cap" },
    { indonesian: "nggak bohong", english: "no cap" },
    { indonesian: "setuju", english: "bet" },
    { indonesian: "fakta", english: "facts" },
    { indonesian: "suasana hati", english: "mood" },
    { indonesian: "cringe", english: "cringe" },
    { indonesian: "memalukan", english: "cringe" },
    { indonesian: "keren banget", english: "fire" },
    { indonesian: "savage", english: "savage" },
    { indonesian: "luar biasa", english: "slay" },
    { indonesian: "ikonik", english: "iconic" },
    { indonesian: "basic", english: "basic" },
    { indonesian: "berlebihan", english: "extra" },
    { indonesian: "menghilang", english: "ghosting" },
    { indonesian: "takut ketinggalan", english: "FOMO" },
    { indonesian: "hidup sekali", english: "YOLO" },
    { indonesian: "mencurigakan", english: "sus" },
    { indonesian: "nonton maraton", english: "binge" },

    // --- Casual Contractions & Shortcuts ---
    { indonesian: "akan", english: "gonna" },
    { indonesian: "ingin", english: "wanna" },
    { indonesian: "harus", english: "gotta" },
    { indonesian: "semacam", english: "kinda" },
    { indonesian: "semacam itu", english: "sorta" },
    { indonesian: "pada dasarnya", english: "pretty much" },
    { indonesian: "sepenuhnya", english: "totally" },
    { indonesian: "jelas sekali", english: "obviously" },
    { indonesian: "pasti ya", english: "for sure" },
    { indonesian: "tidak diragukan", english: "no doubt" },
    { indonesian: "saya kira", english: "I guess" },
    { indonesian: "saya rasa", english: "I suppose" },
    { indonesian: "menurut saya", english: "I reckon" },

    // --- Phrasal Verbs (Very Common) ---
    { indonesian: "mencari tahu", english: "figure out" },
    { indonesian: "berhasil", english: "work out" },
    { indonesian: "ternyata", english: "turn out" },
    { indonesian: "mengetahui", english: "find out" },
    { indonesian: "memeriksa", english: "check out" },
    { indonesian: "nongkrong", english: "hang out" },
    { indonesian: "santai", english: "chill out" },
    { indonesian: "panik", english: "freak out" },
    { indonesian: "kelelahan", english: "burn out" },
    { indonesian: "stres berat", english: "stressed out" },
    { indonesian: "kelelahan total", english: "worn out" },
    { indonesian: "menghadapi", english: "deal with" },
    { indonesian: "mengatasi", english: "cope with" },
    { indonesian: "menangani", english: "handle" },
    { indonesian: "berjuang", english: "struggle" },
    { indonesian: "cocok dengan", english: "vibe with" },
    { indonesian: "terhubung dengan", english: "connect with" },
    { indonesian: "berhubungan dengan", english: "relate to" },
    { indonesian: "beresonansi", english: "resonate" },
    { indonesian: "menyerah", english: "give up" },
    { indonesian: "berbicara lebih keras", english: "speak up" },
    { indonesian: "terbuka", english: "open up" },
    { indonesian: "tenang", english: "calm down" },
    { indonesian: "mengacau", english: "mess up" },
    { indonesian: "merusak", english: "screw up" },
    { indonesian: "datang", english: "show up" },
    { indonesian: "putus", english: "break up" },
    { indonesian: "berbaikan", english: "make up" },
    { indonesian: "bertemu", english: "hook up" },
    { indonesian: "mengobrol", english: "catch up" },

    // --- More Casual Expressions ---
    { indonesian: "hal-hal", english: "stuff" },
    { indonesian: "sesuatu", english: "things" },
    { indonesian: "terserah", english: "whatever" },
    { indonesian: "pokoknya", english: "anyway" },
    { indonesian: "ngobrol", english: "chat" },
    { indonesian: "bercanda", english: "joke" },
    { indonesian: "becanda", english: "kidding" },
    { indonesian: "serius", english: "serious" },
    { indonesian: "beneran", english: "for real" },
    { indonesian: "asli", english: "legit" },
    { indonesian: "palsu", english: "fake" },
    { indonesian: "bercanda kok", english: "just kidding" },
    { indonesian: "gapapa", english: "no worries" },
    { indonesian: "santuy", english: "chill" },
    { indonesian: "kuy", english: "let's go" },
    { indonesian: "gas", english: "go for it" },
    { indonesian: "slow", english: "slow" },
    { indonesian: "ribet", english: "complicated" },
    { indonesian: "simple", english: "simple" },
    { indonesian: "gampang", english: "easy" },
    { indonesian: "susah", english: "hard" },
    
    // --- Internet & Social Media ---
    { indonesian: "viral", english: "viral" },
    { indonesian: "trending", english: "trending" },
    { indonesian: "update", english: "update" },
    { indonesian: "posting", english: "post" },
    { indonesian: "share", english: "share" },
    { indonesian: "like", english: "like" },
    { indonesian: "komen", english: "comment" },
    { indonesian: "follow", english: "follow" },
    { indonesian: "unfollow", english: "unfollow" },
    { indonesian: "block", english: "block" },
    { indonesian: "tag", english: "tag" },
    { indonesian: "mention", english: "mention" },
    { indonesian: "dm", english: "DM" },
    { indonesian: "story", english: "story" },
    { indonesian: "reels", english: "reels" },
    { indonesian: "feed", english: "feed" },
    { indonesian: "scroll", english: "scroll" },
    { indonesian: "swipe", english: "swipe" },
    { indonesian: "screenshot", english: "screenshot" },
    
    // --- Feelings & Reactions (Casual) ---
    { indonesian: "deg-degan", english: "nervous" },
    { indonesian: "excited", english: "excited" },
    { indonesian: "overwhelmed", english: "overwhelmed" },
    { indonesian: "kewalahan", english: "overwhelmed" },
    { indonesian: "awkward", english: "awkward" },
    { indonesian: "canggung", english: "awkward" },
    { indonesian: "malu-maluin", english: "embarrassing" },
    { indonesian: "disappointing", english: "disappointing" },
    { indonesian: "mengecewakan", english: "let down" },
    { indonesian: "kecewa berat", english: "bummed out" },
    { indonesian: "seneng banget", english: "stoked" },
    { indonesian: "gembira", english: "pumped" },
    { indonesian: "bete", english: "annoyed" },
    { indonesian: "dongkol", english: "upset" },
    { indonesian: "kesel", english: "irritated" },
    { indonesian: "jengkel", english: "frustrated" },
    { indonesian: "frustrasi", english: "frustrated" },
    { indonesian: "confused", english: "confused" },
    { indonesian: "bingung", english: "puzzled" },
    
    // --- Time Expressions (Casual) ---
    { indonesian: "nanti", english: "later" },
    { indonesian: "sebentar lagi", english: "in a bit" },
    { indonesian: "bentar", english: "sec" },
    { indonesian: "sekarang juga", english: "right now" },
    { indonesian: "segera", english: "ASAP" },
    { indonesian: "kapan-kapan", english: "sometime" },
    { indonesian: "kadang-kadang", english: "once in a while" },
    { indonesian: "jarang-jarang", english: "rarely" },
    { indonesian: "setiap waktu", english: "all the time" },
    { indonesian: "akhir-akhir ini", english: "these days" },
    { indonesian: "belakangan", english: "lately" },
    { indonesian: "sekarang-sekarang", english: "nowadays" },
    
    // --- Agreement & Support ---
    { indonesian: "iya dong", english: "of course" },
    { indonesian: "pasti", english: "sure thing" },
    { indonesian: "okeh", english: "okay" },
    { indonesian: "siap", english: "roger that" },
    { indonesian: "mantap", english: "cool" },
    { indonesian: "oke sip", english: "sounds good" },
    { indonesian: "setuju banget", english: "totally agree" },
    { indonesian: "betul sekali", english: "exactly" },
    { indonesian: "tepat sekali", english: "spot on" },
    { indonesian: "sama", english: "same" },
    { indonesian: "aku juga", english: "me too" },
    { indonesian: "saya juga", english: "same here" },
    
    // --- Dismissive & Negative Casual ---
    { indonesian: "ah masa", english: "no way" },
    { indonesian: "nggak mungkin", english: "can't be" },
    { indonesian: "mustahil", english: "impossible" },
    { indonesian: "nggak juga", english: "not really" },
    { indonesian: "biasa aja", english: "meh" },
    { indonesian: "cuek", english: "don't care" },
    { indonesian: "bodo amat", english: "whatever" },
    { indonesian: "nggak penting", english: "doesn't matter" },
    { indonesian: "terserah deh", english: "suit yourself" },
    { indonesian: "sesukamu", english: "as you wish" },
    
    // --- Asking & Suggesting (Casual) ---
    { indonesian: "gimana kalau", english: "how about" },
    { indonesian: "mau nggak", english: "wanna" },
    { indonesian: "yuk", english: "let's" },
    { indonesian: "ayo dong", english: "come on" },
    { indonesian: "kenapa nggak", english: "why don't we" },
    { indonesian: "boleh nggak", english: "can I" },
    { indonesian: "bisa nggak", english: "could you" },
    { indonesian: "tolong dong", english: "please" },
    { indonesian: "bantuin dong", english: "help me out" },
    { indonesian: "kasih tau dong", english: "tell me" },
    { indonesian: "jelasin dong", english: "explain it" },
    
    // --- Describing Situations (Casual) ---
    { indonesian: "situasi canggung", english: "awkward situation" },
    { indonesian: "momen keren", english: "epic moment" },
    { indonesian: "drama", english: "drama" },
    { indonesian: "kacau", english: "mess" },
    { indonesian: "berantakan", english: "chaotic" },
    { indonesian: "chaos", english: "chaos" },
    { indonesian: "zonk", english: "fail" },
    { indonesian: "gagal", english: "failed" },
    { indonesian: "sukses", english: "nailed it" },
    { indonesian: "berhasil", english: "pulled it off" },
    { indonesian: "keren abis", english: "awesome" },
    { indonesian: "gokil", english: "crazy" },
    { indonesian: "gila", english: "insane" },
    { indonesian: "parah", english: "terrible" },
    { indonesian: "buruk banget", english: "awful" }
];
